# Site settings
title: David Moody's blog
email: david.doomy@gmail.com
description: "A blog about programming stuff"
baseurl: ""
url: "http://davidxmoody.com"
twitter_username: davidxmoody
github_username:  davidxmoody

# Build settings
markdown: kramdown
permalink: "/:title/"
#future: false
