# Site settings
title: David Moody's blog
email: david@davidxmoody.com
description: "A blog about programming"
url: "http://davidxmoody.com"

# Build settings
markdown: kramdown
permalink: "/:title/"
excerpt_separator: "\n\n\n"
sass:
  style: :compressed
paginate: 6
paginate_path: "/page:num/"
